onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

overrides:
  '@modelcontextprotocol/sdk@>=1.10.0 <=1.25.3': '>=1.26.0'
  ajv@<8.18.0: '>=8.18.0'
  esbuild@<=0.24.2: '>=0.25.0'
  hono@<4.11.7: '>=4.11.7'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@<10.2.1: '>=10.2.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
